name: Create File

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  createFile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Run a one-line script
        run: |
          touch test.txt
          echo "Hello, world!" >>  test.txt
          echo "I'm here" >>  test.txt
          ls -l >>  test.txt
          cat test.txt
          
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/97614556481/locations/global/workloadIdentityPools/identitypool1/providers/wip1'
          service_account: 'gcs-service-account1-284@surfbuddy1.iam.gserviceaccount.com'

      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'test.txt'
          destination: 'surfbuddy_bucket1'
