name: Create File

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  createFile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-line script
        run: |
          touch test.txt
          echo "Hello, world!" >>  test.txt
          echo "I'm here" >>  test.txt
          ls -l >>  test.txt
          cat test.txt
          
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: '/path/to/file'
          destination: 'bucket-name/file'
